#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application();

// ... register commands
$app->add(new \Command\TestCommand());

$app->run();
